# Generated by Django 5.2.8 on 2025-12-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_value', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=80, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_value', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=80, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch_qty', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RollMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.CharField(max_length=50, unique=True)),
                ('qr_value', models.TextField(blank=True, null=True, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('gsm', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='IN_STOCK', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_qr_value', models.TextField()),
                ('current_qr_value', models.TextField()),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['previous_qr_value'], name='track_api_q_previou_e43f23_idx'), models.Index(fields=['current_qr_value'], name='track_api_q_current_558979_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=80, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meters_printed', models.FloatField(blank=True, null=True)),
                ('wastage', models.FloatField(blank=True, null=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_api.rollmaster')),
            ],
        ),
    ]
